### ISSUE TITLE
Deleting nextbots using object context in the context menu

### ISSUE THREAD

**Issue by ghost** [n1clud3/nextbot_run#2]
When you open the context menu and right click on the nextbot's hitbox, you can click on "Remove" and it will completely remove the nextbot from the server. You can do the same (and more) with other entity props like doors.

https://user-images.githubusercontent.com/50070094/209861407-6edb590f-2cb9-475e-8f1a-5443a54f5f66.mp4

**Comment by n1clud3** [comment]
Won't fix as I'm lazy. You can disable it yourself thru removing `properties.lua` in `GarrysMod/garrysmod/lua/autorun`

**Comment by ghost** [comment]
👺
anyways i commented everything in properties.lua and it worked. now the players are angy >:(
